require("config.options") -- [[ Local Nvim options ]]
require("config.shared-options") -- [[ Options shared ]] 
require("config.shared-keymaps") -- [[ Keymaps shared ]]
require("config.keymaps") -- [[ Local Nvim options ]]
require("config.shared-autocommands") -- [[ Autocommands Shared ]]
require("config.lazy") -- [[ Load Lazy ]]
