return {
  "nvim-treesitter/nvim-treesitter",
  event = "LazyFile",
  cmd = { "TSInstall", "TSBufEnable", "TSBufDisable", "TSModuleInfo" },
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "vim",
      "regex",
      "bash",
      "json",
      "json5",
      "jsonc",
      "lua",
      "dockerfile",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "php",
      "regex",
      "sql",
      "yaml",
    },
    sync_install = false,
    highlight = {
      enable = true,
      use_languagetree = true,
      disable = function(_, bufnr) return vim.b[bufnr].large_buf end,
    },
    indent = { enable = true },
  },
  config = function(_, opts) require("nvim-treesitter.configs").setup(opts) end,
}
