return {
  {
    "folke/which-key.nvim",
    dependencies = { "echasnovski/mini.icons", },
    event = "VeryLazy",
    opts = {
      plugins = { spelling = true },
      spec = {
        mode = { "n", "v" },
        { "<leader>n",     group = "note",                desc = "+Note" },
        { "<leader>d",     group = "debug",                desc = "+Debug" },
        { "g",             group = "g",                    desc = "+G" },
        { "]",             group = "next",                 desc = "+Next" },
        { "[",             group = "prev",                 desc = "+Prev" },
        { "<leader><tab>", group = "tabs",                 desc = "+Tabs" },
        { "<leader>b",     group = "buffer",               desc = "+Buffer" },
        { "<leader>c",     group = "code",                 desc = "+Code" },
        { "<leader>f",     group = "file/find",            desc = "+File/Find" },
        { "<leader>g",     group = "git",                  desc = "+Git" },
        { "<leader>gh",    group = "hunks",                desc = "+Hunks" },
        { "<leader>p",     group = "python",         desc = "+Python" },
        { "<leader>pv",     group = "venv",                desc = "+Virtual Environment" },
        { "<leader>q",     group = "quit/session",         desc = "+Quit/Session" },
        { "<leader>s",     group = "search",               desc = "+Search" },
        { "<leader>t",     group = "toggle",               desc = "+Toggle" },
        { "<leader>u",     group = "ui",                   desc = "+Ui" },
        { "<leader>un",    group = "noice",                desc = "+Noice" },
        { "<leader>w",     group = "windows",              desc = "+Windows" },
        { "<leader>x",     group = "diagnostics/quickfix", desc = "+Diagnostics/Quickfix" },
      },
    },
  },
}
